# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Test and build backend

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: go mod download
        working-directory: ./backend

      - name: Ensure dependencies are up-to-date
        run: go mod tidy
        working-directory: ./backend

      - name: Build
        run: go build -v ./...
        working-directory: ./backend

      - name: Test
        run: go test -v ./...
        working-directory: ./backend
